build: seafile-server_2.1.5_x86-64.tar.gz
	docker build -t x3tech/seafile .

seafile-server_2.1.5_x86-64.tar.gz:
	wget https://bitbucket.org/haiwen/seafile/downloads/seafile-server_2.1.5_x86-64.tar.gz
